### ISSUE TITLE
[RFC] Database governance-ConcurrecyControl CRD for concurrency control l | 数据库治理-并发控制

### ISSUE THREAD

**Issue by mlycore** [opensergo/opensergo-specification#33]
domain: database 

Considering change domain to  traffic

Umbrella issue: https://github.com/opensergo/opensergo-specification/issues/15

`ConcurrencyControl` defines a set of rules help declare what to do while meeting some spike traffic.

(English version TBD...)

---

解决的是当具有某个属性特征的 SQL 出现时，对它的出现频率（并发度）进行控制，这样的 SQL 往往是慢 SQL 或者非常消耗资源的 SQL，放任它执行可能会导致关键业务 SQL 无法正常执行。

并发控制包括多种配置规则，比如由工程师根据经验预先设定的 SQL 属性特征，包括正则表达式和条件表达式两种。

在一些场景中，SQL 并发控制表现为开启和关闭两种状态，在开启的情况下，针对特定的 SQL 进行并发数量限制。对于开启状态的判断可以有多种方式，比如通过 Cron 表达式决定生效的时间段。

YAML 示例：
```yaml
apiVersion: database.opensergo.io/v1alpha1
kind: ConcurrencyControl
metadata:
  name: order
spec:
  rules:
  - cron: "* * * * *"
     maxConcurrency: 1
     regex: # 基于正则表达式的
     - "^SELECT * FROM t_orders"
     conditions: # 基于条件表达式的
    - subject: column # column 列或 table 表
      op: in # 预算符，包括 in, eq, ne, notin 等
      values:
      - "items"
```
