### ISSUE TITLE
[RFC] Database governance-Database Discovery CRD for database discovery l | 数据库治理- 数据库发现 

### ISSUE THREAD

**Issue by mlycore** [opensergo/opensergo-specification#38]
domain: database

Umbrella issue: https://github.com/opensergo/opensergo-specification/issues/15

`DatabaseDiscovery` defines a set of rules help discovery database topology and status changes.

(English version TBD...)

---

数据库自动发现指的是根据数据库高可用配置，通过探测的方式感知数据源状态变化，并对流量策略做出相应的调整。比如后端数据源为 MySQL MGR，那么可以配置数据库发现类型为 MYSQL.MGR ，指定 group-name，并配置相应的探测心跳节律。

YAML 示例：
```yaml
apiVersion: database.opensergo.io/v1alpha1
kind: DatabaseDiscovery
metadata:
  name: 
spec:
  dataSources:  
    readwrite_ds:         
      dataSourceNames:
      - ds_0
      - ds_1
      - ds_2
    discoveryHeartbeatName: mgr-heartbeat
    discoveryTypeName: mgr
  discoveryHeartbeats:      # 数据库发现探测心跳
    mgr-heartbeat:
      props:
        "keep-alive-cron": '0/5 * * * * ?'
  discoveryTypes:          # 数据库发现类型
    mgr:
      type: MySQL.MGR
      props:
        "group-name": 92504d5b-6dec-11e8-91ea-246e9612aaf1
```
