### ISSUE TITLE
[RFC] Database governance-DistributedTransaction CRD for distributed transaction l | 数据库治理- 分布式事务

### ISSUE THREAD

**Issue by mlycore** [opensergo/opensergo-specification#39]
domain: database

Umbrella issue: https://github.com/opensergo/opensergo-specification/issues/15

DistributedTransaction defines a set of options defines the algorithm of distributed transaction.

(English version TBD...)

---

声明分布式事务相关的配置，在这里声明事务的类型，没有额外的配置
YAML 示例：

```yaml
apiVersion: database.opensergo.io/v1alpha1
kind: DistributedTransaction
metadata:
  name: mysql-production
spec:
  transaction:
    defaultType: "xa"/"base"/"local"
    providerType: "Narayana"/"Atomikos"/"Seata"
```
