### ISSUE TITLE
[RFC] OpenSergo fault-tolerance spec v1alpha1 proposal | 流控降级与容错标准 v1alpha1

### ISSUE THREAD

**Issue by sczyh30** [opensergo/opensergo-specification#8]
Hi community, I'd like to initiate the discussion regarding the OpenSergo fault-tolerance spec v1alpha1.

![image](https://user-images.githubusercontent.com/9434884/174975858-216af2bd-f071-4351-aa10-6c462ce6d64b.png)

(TBD...)

**Comment by YunWZ** [comment]
> 
```yaml
apiVersion: fault-tolerance.opensergo.io/v1alpha1
kind: FaultToleranceRule
metadata:
  name: my-rule
  namespace: prod
  labels:
    app: my-app # 规则配置生效的应用名
```
建议将匹配生效应用名部分(`app: my-app`)放到spec中，例如`.spec.selector`或者`.spec.selector. matchLabels`。

意义：
1. `metadata`部分应当只用于设置当前`CR`(容错治理规则)的元数据；
2. 保持和其他`CRD`规范的语义一致，避免产生歧义，易于使用--例如Istio中的[Gateway](https://istio.io/latest/docs/reference/config/networking/gateway/)，k8s中的[Deployment](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec)；
